### PR TITLE
Updated to v0.6.0

### PR DESCRIPTION
**Pull request by pelson**
Thanks to @ericdill for the fixes in v0.6.0.

### CODE REVIEW

**Comment by pelson** [comment]
Windows failing:

```
The following NEW packages will be INSTALLED:
    conda:          4.1.4-py27_0   defaults   
    conda-env:      2.5.1-py27_0   defaults   
    conda-execute:  0.6.0-py27_0   local      
    menuinst:       1.4.1-py27_0   defaults   
    pip:            8.1.2-py27_0   defaults   
    psutil:         4.3.0-py27_0   defaults   
    pycosat:        0.6.1-py27_0   conda-forge
    python:         2.7.11-5       defaults   
    pyyaml:         3.11-py27_0    conda-forge
    requests:       2.9.2-py27_0   conda-forge
    ruamel_yaml:    0.11.7-py27_0  defaults   
    setuptools:     23.0.0-py27_0  defaults   
    vs2008_runtime: 9.00.30729.1-2 defaults   
    wheel:          0.29.0-py27_0  defaults   
    yaml:           0.1.6-vc9_0    conda-forge [vc9]
C:\conda\conda-bld\test-tmp_dir>activate _test 
******  B A T C H   R E C U R S I O N  exceeds STACK limits ******
Recursion Count=700, Stack Usage=90 percent
******       B A T C H   PROCESSING IS   A B O R T E D      ******
TESTS FAILED: conda-execute-0.6.0-py27_0
```

**Comment by pelson** [comment]
I'm going to merge as this will fix a couple of known issues with the latest conda. Some thought will be needed for the failing windows cases.

**Comment by msarahan** [comment]
Very interesting. I'll also think on this.

**Comment by msarahan** [comment]
The error is due to a conda bug that is clobbering the activate.bat script in the root environment.  I'm mystified how it didn't show up before, but I'll fix it soon.

**Comment by msarahan** [comment]
Proposed fix in https://github.com/conda/conda/pull/2938 - seems to work locally.

**Comment by pelson** [comment]
Amazing. Thanks @msarahan! :+1:  (though I obviously haven't tested it)

**Pull request merged**
