### PR TITLE
Update to v0.5.0...

### PR DESCRIPTION
**Pull request by ocefpaf**
... re-rendered with https://github.com/conda-forge/conda-smithy/pull/199

### CODE REVIEW

**Comment by ocefpaf** [comment]
@pelson any idea why AppVeyor is hanging forever for PY27 and PY35?

**Comment by pelson** [comment]
Afraid not, but I saw similar symptoms yesterday where freezing on resolve. I've restarted, and wonder if something is wrong with conda / conda-build etc.

**Comment by ocefpaf** [comment]
I canceled b/c it was hanging again... :unamused:

**Comment by pelson** [comment]
Thanks @ocefpaf. 

It isn't good that the test is stalling in this way...

```
TEST START: conda-execute-0.5.0-py27_0
Using Anaconda Cloud api site https://api.anaconda.org 
Fetching package metadata ........... 
Solving package specifications: .......... 

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    yaml-0.1.6                 |            vc9_0          80 KB  conda-forge
    conda-env-2.5.1            |           py27_0          63 KB  defaults 
    menuinst-1.4.1             |           py27_0         102 KB  defaults
    pycosat-0.6.1              |           py27_0          41 KB  conda-forge 
    pyyaml-3.11                |           py27_0         112 KB  conda-forge
    requests-2.9.2             |           py27_0         584 KB  conda-forge
    conda-execute-0.5.0        |           py27_0          58 KB  local
    ------------------------------------------------------------ 
                                           Total:         1.0 MB

The following NEW packages will be INSTALLED: 

    conda:          4.1.2-py27_0   defaults    
    conda-env:      2.5.1-py27_0   defaults   
    conda-execute:  0.5.0-py27_0   local      
    menuinst:       1.4.1-py27_0   defaults    
    pip:            8.1.2-py27_0   defaults   
    psutil:         4.3.0-py27_0   defaults    
    pycosat:        0.6.1-py27_0   conda-forge 
    python:         2.7.11-4       defaults   
    pyyaml:         3.11-py27_0    conda-forge
    requests:       2.9.2-py27_0   conda-forge
    ruamel_yaml:    0.11.7-py27_0  defaults    
    setuptools:     23.0.0-py27_0  defaults   
    vs2008_runtime: 9.00.30729.1-1 defaults    
    wheel:          0.29.0-py27_0  defaults   
    yaml:           0.1.6-vc9_0    conda-forge [vc9]

<STALL FOR >1hr>
```

Have you seen anything like this since the conda-build/conda releases @msarahan?

**Comment by ocefpaf** [comment]
No need for this with #8

**Comment by pelson** [comment]
Sorry @ocefpaf - the curse of too many issues/notifications. I didn't remember about this one. Thanks for referencing the two, and thanks for the initial PR! :+1:

**Comment by ocefpaf** [comment]
No biggie. I forgot about this myself. Just trying yo understand the Windows issue now as I really need that solved :grimacing:

**Comment by pelson** [comment]
Agreed. It is somewhat worrying.

**Comment by msarahan** [comment]
I have seen hangs in the xerces-c staged recipe, but never with a Python
2.7 install. Can you add debug, like:

Conda --debug update ...

(we can also just copy this pr and do it ourselves if you want)

Cc @mcg1969 @kalefranz

**Comment by msarahan** [comment]
I wonder if this has anything to do with corrupted installs like
https://github.com/conda/conda/issues/2913

**Comment by msarahan** [comment]
Maybe also: https://github.com/conda/conda/issues/2912

**Comment by ocefpaf** [comment]
> I have seen hangs in the xerces-c staged recipe, but never with a Python
> 2.7 install.

@msarahan I believe the error here was similar to the one we saw in `conda-build-all` and `obvious-ci`. However, we have a new one in #8 and this the problem here is "gone."

**Pull request closed without merging**
